# Builds using pip and tests using pytest

name: OxPy Linux

on: push

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        py: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.py}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install numpy
    - name: Build oxDNA, install and reinstall oxpy
      run: |
        mkdir build && pushd build
        cmake .. -DCUDA=0 -DPython=1 -DPYBIND11_PYTHON_VERSION=${{matrix.py}}
        make -j2
        make install
        pip uninstall oxpy -y
        make install
        popd
    - name: Check import from Command Line
      run: |
        mkdir test-folder && pushd test-folder
        python -c 'import oxpy'

